spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Brazil/East
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true
    flyway:
      enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: lista-rabbit
    password: 1234567
  cache:
    type: redis
    cache-names: listarHistoricoDeItensPorItemId,listaDeLocais,listaDeCompra,listaDeItens,listaDeItemPorNome
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
logging:
  level:
    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  public:
    key: classpath:app.pub

  private:
    key: classpath:app.key
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 5

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/compras
    username: postgres
    password: 1234567
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORTA}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

logging:
  level:
    root: INFO
    com.example.mypackage: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
