name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  criar-projeto:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verificar dependências
        run: mvn dependency:resolve

      - name: Construir com Maven
        run: mvn -B clean install

  executar-testes:
    runs-on: ubuntu-latest
    needs: criar-projeto

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Executar testes
        run: mvn test

  deploy-imagem-docker-hub:
    runs-on: ubuntu-latest
    needs: executar-testes

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verificar dependências e package
        run: mvn package

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: extrair versão do pom
        id: extract_version
        run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build imagem docker
        run: |
          docker build . --file Dockerfile --tag listadecompra:${{ env.PROJECT_VERSION }}

      - name: Deploy image
        run: |
          docker tag listadecompra:${{ env.PROJECT_VERSION }} gacacio/listadecompra:${{ env.PROJECT_VERSION }}
          docker push gacacio/listadecompra:${{ env.PROJECT_VERSION }}

  incrementar-versao:
    runs-on: ubuntu-latest
    needs: deploy-imagem-docker-hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Increment version in pom.xml
        id: increment_version
        run: |
          current_version=$(xmllint --xpath "//*[local-name()='version']/text()" pom.xml | head -n 1)
          IFS='.' read -r -a version_parts <<< "$current_version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_minor=$((minor + 1))
          new_version="$major.$new_minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$new_version

      - name: Commit and push version increment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pom.xml
          git commit -m "Subindo versão para ${{ env.new_version }}"
          git push