name: Continuos Integration

on:
  push:
    branches:
      - 'G*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build project
        run: mvn -B clean install

      - name: Verificar dependências
        run: mvn dependency:resolve
