name: Continuos Integration

on:
  push:
    branches:
      - 'G*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v5

      - name: Configurar JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verificar dependências
        run: mvn dependency:resolve

      - name: Construir com Maven
        run: mvn -B clean compile

  testar:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v5

      - name: Configurar JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Executar testes
        run: mvn test